#!/usr/bin/env python
# $Id: reBranch.py,v 1.50 2009-10-16 08:11:59 modtest Exp $
"""
Created on 2010-05-13

@author: pstrycha
"""

import os
import sys

    

dirs = []
counter = 1

currentPath = os.getcwd()
entries = os.listdir(currentPath)
    
for e in entries:
    if os.path.isdir(e):
        dirs.append(e)
        
for d in dirs:
    print("Checking '" + d + "' directory[" + str(counter) + "/" + str(len(dirs)) + "].")
    counter = counter + 1

    info = os.popen("svn info " + d)
    for i in info.readlines():
        firstToken = i.split()[0]
        if firstToken == "URL:":
            baseUrl = i.split()[1]
            if baseUrl.find("branches") != -1:
                splitStr = "branches"
            elif baseUrl.find("trunk") != -1:
                splitStr = "trunk"
            elif baseUrl.find("tags") != -1:
                splitStr = "tags"
            else:
                break
            
            firstPart = baseUrl.split(splitStr)[0]
            secondPart = baseUrl.split(splitStr)[1]
            

            if d == ".svn":
                break

            cmdToExecute = "svn up" + " " + d
            print("Updating '" + d + "' subdir to HEAD'")
            os.system(cmdToExecute)
            break

